deploy:
  provider: codedeploy
  access_key_id: "AKIAJHVHQI3ZTNOD2F3Q"
  secret_access_key: "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"
  bucket: "S3 Bucket"
  key: latest/MyApp.zip
  application: MyApp
  deployment_group: MyDeploymentGroup

language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install:
  - "pip install iso8601"
  - "pip install ."
  - "pip install -r requirements.txt"
# command to run tests
script: nosetests
